---
site_title: Rochester Security Summit
# current conference year - used to show current information and to prevent
# current/upcoming conference from showing on past events page
current_year: 2023

# previous conference year
previous_year: 2022

# next conference year - leave at current during early planning
next_year: 2024

# conference dates
conference_start_date: 2022-10-25
conference_end_date: 2022-10-26

# which year's sponsors should be shown on the homepage
# allows for previous year's to show until the current year's list is ready
homepage_sponsors_show_current_year: true
homepage_sponsors_show_previous_year: false

# should the pre-conference "coming soon" message be shown on the homepage?
homepage_conference_announcement: false

# should the venue info be displayed on the homepage?
homepage_show_venue: true

# should the hotel info be displayed on the homepage?
homepage_show_hotels: true

# should keynote speakers be shown on homepage?
homepage_show_keynotes: true

# should app links be shown on the homepage
homepage_show_app_links: true
app_ios_url: https://apps.apple.com/us/app/id1478439812
app_android_url: https://play.google.com/store/apps/details?id=com.guidebook.apps.rss.android
app_web_url: https://guidebook.com/g/rss2023

homepage_show_post_conference_info: false

homepage_show_call_for_volunteers: true
homepage_show_schedule_link: true




# should registration info be displayed on the homepage?
registration_not_yet_open: false
registration_enabled: true
registration_early_bird: false
registration_standard: true
registration_late: true
registration_sold_out: false
registration_event_concluded: false


# sponsorship messaging
sponsorship_show_w9_link: false
sponsorship_next_year: false
sponsorship_not_yet_open: false
sponsorship_coming_soon: false
sponsorship_open: false
sponsorship_waiting_list: true  # sold out, but accepting to waiting list
sponsorship_sold_out: false
sponsorship_pricing: true
sponsorship_sponsor_information: false
sponsorship_attendee_profile: true
sponsorship_faq: false

# sponsorship key dates



# speaking messaging
speaking_next_year: false
speaking_cfp_not_yet_open: false
speaking_cfp_open: true
speaking_cfp_closed: false
speaking_show_guidelines: false
speaking_show_key_dates: false

# speaking key dates
speaking_proposals_due: 2022-08-01
speaking_committee_responses: 2022-08-15
speaking_materials_due: 2022-09-01
speaking_presentation_due: 2022-09-15

schedule_not_yet_available: false
schedule_tentative: true
schedule_available: true